# Generated by Django 5.2.4 on 2026-04-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(default='6285195564668', help_text='Format: 628xxx (tanpa + atau 0)', max_length=20)),
                ('whatsapp_display', models.CharField(default='+62 851-9556-4668', max_length=50)),
                ('email', models.EmailField(default='info@aji-institute.id', max_length=254)),
                ('instagram', models.CharField(default='@ajiinstitute.id', max_length=50)),
                ('address', models.TextField(default='Kompleks Bandung Indah Raya Blok C7 No.1, Kel. Mekarjaya, Kec. Rancasari, Bandung')),
                ('operational_hours', models.CharField(default='24 Jam / 7 Hari', max_length=100)),
            ],
            options={
                'verbose_name': 'Company Setting',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('badge_text', models.CharField(default='Info Terbaru', max_length=50)),
                ('image', models.ImageField(help_text='Gambar latar banner', upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama divisi atau individu (misal: Aji Pamoso atau Tim Fasilitator AjiStat)', max_length=100)),
                ('role', models.CharField(help_text='Jabatan atau fungsi (misal: CEO Aji Institute)', max_length=100)),
                ('initials', models.CharField(help_text='Inisial jika tidak ada foto (misal: AP atau ST)', max_length=5)),
                ('accent_color', models.CharField(default='#1B3A8C', help_text='Warna utama (Hex, misal: #1B3A8C)', max_length=20)),
                ('accent_light', models.CharField(default='#EEF2FF', help_text='Warna latar/muda (Hex, misal: #EEF2FF)', max_length=20)),
                ('description', models.TextField(help_text='Deskripsi singkat untuk di kartu')),
                ('detail', models.TextField(help_text='Deskripsi panjang untuk di pop-up modal')),
                ('tags', models.CharField(help_text='Pisahkan dengan koma (misal: SPSS, SmartPLS, AMOS)', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Foto/Logo tim (Optional)', null=True, upload_to='teams/')),
                ('is_ceo', models.BooleanField(default=False, help_text='Centang jika ini adalah profil CEO (akan tampil di section besar atas)')),
                ('order', models.IntegerField(default=0, help_text='Urutan tampil (makin kecil makin atas)')),
            ],
            options={
                'verbose_name': 'Team & Division',
                'verbose_name_plural': 'Teams & Divisions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='Misal: Mahasiswa S2 UGM', max_length=100)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_featured', models.BooleanField(default=True, help_text='Tampilkan di halaman utama')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ToolLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('use_for', models.TextField(help_text='Kegunaan (misal: Uji asumsi, regresi, dll)')),
                ('color', models.CharField(default='#1B3A8C', max_length=20)),
                ('image', models.ImageField(upload_to='tools/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
