# Generated by Django 5.2.4 on 2026-04-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='cta2_link',
            field=models.CharField(default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='cta2_text',
            field=models.CharField(default='Hubungi Kami', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='cta_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='cta_link',
            field=models.CharField(default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='cta_text',
            field=models.CharField(default='Lihat Program →', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='overlay_gradient',
            field=models.CharField(default='from-[#162058]/90 via-[#1B3A8C]/75 to-transparent', max_length=100),
        ),
    ]
