# Generated by Django 5.2.4 on 2026-04-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_herobanner_cta2_link_herobanner_cta2_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='chips',
            field=models.CharField(blank=True, help_text='Koma terpisah, misal: SPSS,SmartPLS', max_length=200),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stats',
            field=models.CharField(blank=True, help_text='Format: Nilai|Label, misal: 10+|Tools, 5|Format', max_length=200),
        ),
    ]
