# Generated by Django 5.2.4 on 2026-05-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_popup_slide_duration_alter_companyconfig_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyconfig',
            name='whatsapp_template',
            field=models.TextField(blank=True, default='Halo Tim *{divisi}*,\n\n{konteks}\n\nBerikut data saya:\nNama:\nJurusan/Fakultas/Universitas:\nLembaga/Instansi:\nKebutuhan (konsultasi/bootcamp/kelas private/dll):\n\nMohon informasinya. Terima kasih.', help_text='Gunakan {divisi} untuk nama divisi otomatis, dan {konteks} untuk niat/judul otomatis. Kosongkan untuk format default.', null=True),
        ),
    ]
