# Generated by Django 6.0.3 on 2026-03-27 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('bootcamp', 'Bootcamp'), ('short-class', 'Short Class'), ('private-class', 'Private Class')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Akan Dilaksanakan'), ('ongoing', 'Sedang Berlangsung'), ('recorded', 'Rekaman Tersedia')], default='upcoming', max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('curriculum', models.JSONField(default=list)),
                ('facilitator_name', models.CharField(blank=True, max_length=100)),
                ('facilitator_title', models.CharField(blank=True, max_length=200)),
                ('facilitator_bio', models.TextField(blank=True)),
                ('facilitator_avatar', models.CharField(blank=True, max_length=10)),
                ('demo_video_url', models.URLField(blank=True)),
                ('thumbnail_color', models.CharField(default='#162660', max_length=7)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('schedule', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('program_name', models.CharField(blank=True, max_length=200)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('avatar', models.CharField(blank=True, max_length=10)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='programs.program')),
            ],
        ),
    ]
