# Generated by Django 5.2.4 on 2026-04-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_add_brand_field_fix_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='brand',
            field=models.CharField(choices=[('ajistat', 'AjiStat — Statistika & Riset'), ('ajibiz', 'AjiBiz — Bisnis & Kewirausahaan'), ('ajicomm', 'AjiComm — Public Relations & Komunikasi'), ('ajiai', 'AjiAI — Digital Marketing & AI'), ('ajilingua', 'AjiLingua — Bahasa & Komunikasi')], default='ajistat', help_text='Kategori brand program ini (AjiStat, AjiBiz, dll)', max_length=20, verbose_name='Brand / Sub-program'),
        ),
    ]
