# Generated by Django 5.2.13 on 2026-05-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_program_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='brand',
            field=models.CharField(choices=[('aji-institute', 'Aji Institute — Layanan Langsung'), ('ajistat', 'AjiStat — Statistika & Riset'), ('ajibiz', 'AjiBiz — Bisnis & Kewirausahaan'), ('ajicomm', 'AjiComm — Public Relations & Komunikasi'), ('ajiai', 'AjiAI — Digital Marketing & AI'), ('ajilingua', 'AjiLingua — Bahasa & Komunikasi')], default='ajistat', help_text='Kategori brand program ini (AjiStat, AjiBiz, dll)', max_length=20, verbose_name='Brand / Sub-program'),
        ),
    ]
