# Generated by Django 5.2.4 on 2026-05-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_alter_program_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, help_text='Gambar/Flyer Program (Opsional)', null=True, upload_to='programs/'),
        ),
    ]
