# Generated by Django 5.2.13 on 2026-05-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_program_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='rundown',
            field=models.JSONField(blank=True, default=list, help_text='Format: [{"day": "Hari 1", "time": "08.00 - 12.00", "label": "Sesi Pagi", "note": "Materi"}]'),
        ),
    ]
