# Generated by Django 5.2.4 on 2026-05-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_program_rundown'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['order', '-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='program',
            name='order',
            field=models.IntegerField(default=0, help_text='Urutan tampil (angka terkecil tampil duluan)'),
        ),
    ]
