# Generated by Django 5.2.13 on 2026-05-31 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_alter_program_options_program_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='show_documentation',
            field=models.BooleanField(default=False, help_text='Aktifkan untuk menampilkan section foto dokumentasi di halaman program', verbose_name='Tampilkan Dokumentasi Pelatihan?'),
        ),
        migrations.CreateModel(
            name='ProgramDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documentation/', verbose_name='Foto Dokumentasi')),
                ('caption', models.CharField(blank=True, help_text='Opsional — keterangan singkat foto (contoh: Sesi coding NVivo hari ke-2)', max_length=200, verbose_name='Keterangan Foto')),
                ('order', models.PositiveIntegerField(default=0, help_text='Angka terkecil tampil duluan', verbose_name='Urutan')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_images', to='programs.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Foto Dokumentasi',
                'verbose_name_plural': 'Foto Dokumentasi',
                'ordering': ['order'],
            },
        ),
    ]
