# Generated by Django 5.2.4 on 2026-06-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_program_show_documentation_programdocumentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='URL video YouTube (contoh: https://youtu.be/xxxxx atau https://www.youtube.com/watch?v=xxxxx)', null=True, verbose_name='Link Video YouTube'),
        ),
    ]
