# Generated by Django 5.2.4 on 2026-06-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_add_youtube_url_to_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='RisetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Proyek')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('client', models.CharField(blank=True, max_length=255, verbose_name='Klien / Instansi')),
                ('description', models.TextField(verbose_name='Deskripsi Proyek')),
                ('scope', models.JSONField(blank=True, default=list, help_text='Contoh: ["Sosial Budaya", "Ekonomi", "Hankam"]', verbose_name='Bidang Riset')),
                ('methodology', models.JSONField(blank=True, default=list, help_text='Contoh: ["Survei", "Wawancara Mendalam", "FGD"]', verbose_name='Metodologi')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Lokasi')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Tahun Pelaksanaan')),
                ('status', models.CharField(choices=[('ongoing', 'Sedang Berlangsung'), ('completed', 'Selesai')], default='ongoing', max_length=20, verbose_name='Status Proyek')),
                ('image', models.ImageField(blank=True, null=True, upload_to='riset/', verbose_name='Cover Image Proyek')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tampilkan sebagai Unggulan?')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publikasikan?')),
                ('order', models.IntegerField(default=0, verbose_name='Urutan Tampil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyek Riset',
                'verbose_name_plural': 'Proyek Riset',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
