# Generated by Django 6.0.5 on 2026-06-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_add_risetproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck untuk menyembunyikan program dari website tanpa menghapus datanya', verbose_name='Tampilkan di Website?'),
        ),
    ]
