# Generated by Django 6.0.5 on 2026-06-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_add_is_published_to_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='youtube_url_2',
            field=models.URLField(blank=True, help_text='URL video YouTube kedua/tambahan (opsional)', null=True, verbose_name='Link Video YouTube ke-2'),
        ),
        migrations.AlterField(
            model_name='program',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='URL video YouTube pertama (contoh: https://youtu.be/xxxxx)', null=True, verbose_name='Link Video YouTube ke-1'),
        ),
    ]
