"""
AjiStat — Seed Data Script
Run: python manage.py shell < apps/seed.py
"""
import os, sys, django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')

from apps.programs.models import Program, Testimonial

# Clear existing
Program.objects.all().delete()
Testimonial.objects.all().delete()

programs = [
    # ─── BOOTCAMP ────────────────────────────────────────────
    {
        "title": "Bootcamp Analisis Data dengan SPSS: Dari Dasar hingga Mahir",
        "slug": "bootcamp-spss-dasar-mahir",
        "type": "bootcamp",
        "description": "Kuasai SPSS untuk kebutuhan riset akademik dan profesional. Dari instalasi, input data, statistik deskriptif, uji asumsi, hingga regresi dan interpretasi hasil yang siap masuk laporan.",
        "price": 350000,
        "original_price": 500000,
        "status": "upcoming",
        "tags": ["SPSS", "Statistik", "Riset", "Pemula"],
        "curriculum": [
            "Pengenalan SPSS dan antarmuka",
            "Input & cleaning data",
            "Statistik deskriptif & frekuensi",
            "Uji normalitas & homogenitas",
            "Uji beda: T-test, ANOVA",
            "Korelasi & regresi linier",
            "Interpretasi & pelaporan hasil",
        ],
        "facilitator_name": "Dr. Ahmad Fauzan, M.Stat",
        "facilitator_title": "Dosen Statistika, Peneliti Kuantitatif",
        "facilitator_bio": "10+ tahun pengalaman mengajar statistika. Penulis 30+ artikel terindeks Scopus.",
        "facilitator_avatar": "AF",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#162660",
        "duration": "4 Hari (8 Sesi Live Zoom)",
        "schedule": "10 April 2026",
        "is_featured": True,
    },
    {
        "title": "Bootcamp SmartPLS: Structural Equation Modeling untuk Riset",
        "slug": "bootcamp-smartpls-sem",
        "type": "bootcamp",
        "description": "Pelajari metode SEM-PLS untuk penelitian bisnis, manajemen, dan sosial. Dari desain model, outer loading, AVE, CR, hingga uji hipotesis bootstrapping.",
        "price": 400000,
        "original_price": 600000,
        "status": "upcoming",
        "tags": ["SmartPLS", "SEM", "Kuantitatif"],
        "curriculum": [
            "Pengenalan SEM dan SmartPLS",
            "Desain model reflektif & formatif",
            "Measurement model: outer loading, AVE, CR",
            "Structural model: path coefficient",
            "Bootstrapping & uji hipotesis",
            "Mediasi & moderasi",
            "Pelaporan hasil SEM",
        ],
        "facilitator_name": "Dr. Rizky Pratama, M.M",
        "facilitator_title": "Pakar SEM & Metodologi Penelitian",
        "facilitator_bio": "Konsultan riset untuk lebih dari 200 tesis dan disertasi S2/S3.",
        "facilitator_avatar": "RP",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#2568B5",
        "duration": "3 Hari (6 Sesi Live Zoom)",
        "schedule": "17 April 2026",
        "is_featured": True,
    },
    {
        "title": "Bootcamp R Studio: Analisis Statistika Lanjutan untuk Peneliti",
        "slug": "bootcamp-r-studio-lanjutan",
        "type": "bootcamp",
        "description": "Analisis data lanjutan dengan R: regresi lanjut, clustering, PCA, hingga visualisasi publikasi-grade dengan ggplot2.",
        "price": 450000,
        "original_price": 650000,
        "status": "upcoming",
        "tags": ["R", "Data Science", "Visualisasi"],
        "curriculum": [
            "Setup R & RStudio",
            "Manipulasi data dengan dplyr",
            "Visualisasi dengan ggplot2",
            "Regresi lanjut & GLM",
            "Analisis kluster",
            "PCA & dimensionality reduction",
            "Membuat laporan dengan R Markdown",
        ],
        "facilitator_name": "Siti Nuraini, M.Si",
        "facilitator_title": "Data Scientist & Peneliti Biostatistik",
        "facilitator_bio": "Praktisi data science dengan pengalaman riset di bidang kesehatan dan sosial.",
        "facilitator_avatar": "SN",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#1a4a8a",
        "duration": "5 Hari (10 Sesi Live Zoom)",
        "schedule": "24 April 2026",
        "is_featured": True,
    },
    {
        "title": "Bootcamp Python untuk Analisis Data dan Machine Learning Dasar",
        "slug": "bootcamp-python-data-ml",
        "type": "bootcamp",
        "description": "Mulai dari Python dasar hingga pandas, numpy, scikit-learn untuk analisis data dan model ML sederhana.",
        "price": 500000,
        "original_price": 750000,
        "status": "upcoming",
        "tags": ["Python", "Machine Learning", "Data Science"],
        "curriculum": [
            "Python dasar untuk data",
            "Pandas & numpy",
            "Eksplorasi data (EDA)",
            "Visualisasi dengan matplotlib & seaborn",
            "Preprocessing data",
            "Model regresi & klasifikasi",
            "Evaluasi model",
        ],
        "facilitator_name": "Bima Aditya, M.Kom",
        "facilitator_title": "ML Engineer & Data Science Educator",
        "facilitator_bio": "Pengalaman 7 tahun di industri teknologi, trainer bersertifikat Google.",
        "facilitator_avatar": "BA",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#0C1A45",
        "duration": "5 Hari (10 Sesi Live Zoom)",
        "schedule": "1 Mei 2026",
        "is_featured": False,
    },
    {
        "title": "Bootcamp Metodologi Penelitian Kuantitatif Komprehensif",
        "slug": "bootcamp-metodologi-kuantitatif",
        "type": "bootcamp",
        "description": "Dari latar belakang masalah, kerangka teori, instrumen, pengumpulan data, analisis hingga penarikan kesimpulan yang valid dan terstruktur.",
        "price": 350000,
        "original_price": 500000,
        "status": "recorded",
        "tags": ["Metodologi", "Kuantitatif", "Skripsi", "Tesis"],
        "curriculum": [
            "Filsafat penelitian kuantitatif",
            "Perumusan masalah & hipotesis",
            "Desain penelitian & sampling",
            "Instrumen & uji validitas-reliabilitas",
            "Teknik pengumpulan data",
            "Analisis & interpretasi",
            "Penulisan laporan penelitian",
        ],
        "facilitator_name": "Prof. Dr. Hendra Wijaya",
        "facilitator_title": "Guru Besar Metodologi Penelitian",
        "facilitator_bio": "Penulis buku metodologi penelitian yang digunakan di 50+ universitas Indonesia.",
        "facilitator_avatar": "HW",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#162660",
        "duration": "4 Hari Rekaman",
        "schedule": "Akses Seumur Hidup",
        "is_featured": False,
    },
    {
        "title": "Bootcamp Penulisan Artikel Ilmiah & Strategi Publikasi Scopus",
        "slug": "bootcamp-publikasi-scopus",
        "type": "bootcamp",
        "description": "Strategi menulis, mereview, dan mempublikasikan artikel ke jurnal terindeks Scopus dan Web of Science. Termasuk manuscript preparation dan response to reviewer.",
        "price": 450000,
        "original_price": 700000,
        "status": "upcoming",
        "tags": ["Scopus", "Publikasi", "Akademik"],
        "curriculum": [
            "Struktur artikel ilmiah internasional",
            "Pemilihan jurnal target",
            "Strategi penulisan abstract & keywords",
            "Literature review yang kuat",
            "Metodologi & hasil yang meyakinkan",
            "Response to reviewer",
            "Etika publikasi ilmiah",
        ],
        "facilitator_name": "Dr. Laila Maharani, M.Hum",
        "facilitator_title": "Editor Jurnal Internasional, H-index 12",
        "facilitator_bio": "Reviewer di 15+ jurnal terindeks Scopus. Membantu 100+ artikel berhasil dipublikasikan.",
        "facilitator_avatar": "LM",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#2568B5",
        "duration": "3 Hari (6 Sesi Live Zoom)",
        "schedule": "8 Mei 2026",
        "is_featured": False,
    },
    # ─── SHORT CLASS ──────────────────────────────────────────
    {
        "title": "Uji Validitas & Reliabilitas Instrumen dengan SPSS dalam 2 Jam",
        "slug": "short-validitas-reliabilitas-spss",
        "type": "short-class",
        "description": "Sesi singkat 2 jam: pelajari cara menguji validitas (pearson/corrected item-total) dan reliabilitas (cronbach alpha) instrumen penelitian dengan SPSS secara langsung.",
        "price": 99000,
        "original_price": 150000,
        "status": "upcoming",
        "tags": ["SPSS", "Validitas", "Pemula"],
        "curriculum": [
            "Konsep validitas & reliabilitas",
            "Input data kuesioner ke SPSS",
            "Uji validitas pearson",
            "Uji reliabilitas cronbach alpha",
            "Interpretasi & pelaporan",
        ],
        "facilitator_name": "Dr. Ahmad Fauzan, M.Stat",
        "facilitator_title": "Dosen Statistika",
        "facilitator_bio": "Spesialis instrumen penelitian dan analisis data.",
        "facilitator_avatar": "AF",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#4FA8D8",
        "duration": "2 Jam",
        "schedule": "5 April 2026",
        "is_featured": True,
    },
    {
        "title": "Visualisasi Data untuk Laporan Ilmiah dengan Python & Matplotlib",
        "slug": "short-visualisasi-python",
        "type": "short-class",
        "description": "Buat grafik dan chart publikasi-grade untuk skripsi, tesis, dan artikel ilmiah menggunakan Python, Matplotlib, dan Seaborn dalam 2 jam intensif.",
        "price": 120000,
        "original_price": 200000,
        "status": "upcoming",
        "tags": ["Python", "Visualisasi", "Intermediate"],
        "curriculum": [
            "Setup library matplotlib & seaborn",
            "Bar chart, line chart, scatter plot",
            "Boxplot & distribusi",
            "Kustomisasi warna & style akademik",
            "Export gambar resolusi tinggi",
        ],
        "facilitator_name": "Bima Aditya, M.Kom",
        "facilitator_title": "ML Engineer & Data Visualizer",
        "facilitator_bio": "Spesialis visualisasi data dan storytelling dengan Python.",
        "facilitator_avatar": "BA",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#4FA8D8",
        "duration": "2 Jam",
        "schedule": "12 April 2026",
        "is_featured": True,
    },
    {
        "title": "Cara Cepat Temukan Artikel Scopus Relevan dengan Teknik Boolean",
        "slug": "short-scopus-boolean-search",
        "type": "short-class",
        "description": "Kuasai teknik pencarian database Scopus, Web of Science, dan Google Scholar menggunakan boolean operator dan keyword strategy untuk literatur review yang komprehensif.",
        "price": 85000,
        "original_price": 130000,
        "status": "recorded",
        "tags": ["Scopus", "Literatur", "Akademik"],
        "curriculum": [
            "Boolean operator: AND, OR, NOT",
            "Pencarian di Scopus & WOS",
            "Filter berdasarkan subject area & kuartil",
            "Export referensi ke Mendeley/Zotero",
            "Tips literatur review sistematis",
        ],
        "facilitator_name": "Dr. Laila Maharani, M.Hum",
        "facilitator_title": "Editor Jurnal Internasional",
        "facilitator_bio": "Ahli strategi pencarian literatur ilmiah.",
        "facilitator_avatar": "LM",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#162660",
        "duration": "1.5 Jam Rekaman",
        "schedule": "Akses Seumur Hidup",
        "is_featured": False,
    },
    {
        "title": "Analisis Regresi Logistik dengan SPSS untuk Penelitian Kesehatan",
        "slug": "short-regresi-logistik-spss",
        "type": "short-class",
        "description": "Sesi khusus regresi logistik biner dan multinomial untuk penelitian klinis dan kesehatan masyarakat menggunakan SPSS. Termasuk interpretasi Odds Ratio.",
        "price": 149000,
        "original_price": 220000,
        "status": "upcoming",
        "tags": ["SPSS", "Kesehatan", "Regresi"],
        "curriculum": [
            "Konsep regresi logistik",
            "Asumsi & prasyarat",
            "Regresi logistik biner di SPSS",
            "Interpretasi odds ratio & CI",
            "Uji goodness of fit",
        ],
        "facilitator_name": "Dr. Ahmad Fauzan, M.Stat",
        "facilitator_title": "Biostatistician",
        "facilitator_bio": "Konsultan biostatistik untuk penelitian kesehatan masyarakat.",
        "facilitator_avatar": "AF",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#2568B5",
        "duration": "3 Jam",
        "schedule": "19 April 2026",
        "is_featured": False,
    },
    {
        "title": "Penulisan Bab IV & V Skripsi: Hasil, Pembahasan, dan Kesimpulan",
        "slug": "short-penulisan-bab-4-5",
        "type": "short-class",
        "description": "Panduan praktis menulis bab hasil dan pembahasan yang kuat dan tidak plagiat: cara menyajikan data, menganalisis, mendiskusikan, dan menarik kesimpulan yang tepat.",
        "price": 99000,
        "original_price": 150000,
        "status": "recorded",
        "tags": ["Skripsi", "Penulisan", "Akademik", "Pemula"],
        "curriculum": [
            "Struktur bab IV & V yang benar",
            "Cara menyajikan tabel & gambar",
            "Menulis pembahasan yang kuat",
            "Menghindari plagiarisme",
            "Kesimpulan & saran yang tepat",
        ],
        "facilitator_name": "Prof. Dr. Hendra Wijaya",
        "facilitator_title": "Guru Besar Metodologi",
        "facilitator_bio": "Pembimbing ratusan skripsi dan tesis S1/S2.",
        "facilitator_avatar": "HW",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#1a4a8a",
        "duration": "2 Jam Rekaman",
        "schedule": "Akses Seumur Hidup",
        "is_featured": True,
    },
    {
        "title": "NVivo untuk Analisis Data Kualitatif: Koding & Tema",
        "slug": "short-nvivo-kualitatif",
        "type": "short-class",
        "description": "NVivo untuk penelitian kualitatif: import data wawancara/FGD, koding tematik, membuat node, dan mengekspor hasil analisis yang siap dilaporkan.",
        "price": 175000,
        "original_price": 250000,
        "status": "upcoming",
        "tags": ["NVivo", "Kualitatif", "Intermediate"],
        "curriculum": [
            "Pengenalan NVivo & interface",
            "Import data teks & audio",
            "Koding manual & otomatis",
            "Membuat nodes & themes",
            "Visualisasi: word cloud & matrix",
            "Export hasil analisis",
        ],
        "facilitator_name": "Siti Nuraini, M.Si",
        "facilitator_title": "Peneliti Kualitatif Bersertifikat",
        "facilitator_bio": "Spesialis analisis data kualitatif dan mixed methods.",
        "facilitator_avatar": "SN",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#4FA8D8",
        "duration": "3 Jam",
        "schedule": "26 April 2026",
        "is_featured": False,
    },
]

for p in programs:
    Program.objects.create(**p)

print(f"✓ Created {len(programs)} programs")

testimonials = [
    {"name": "Rika Amalia", "role": "Mahasiswi S2 Manajemen, UGM", "program_name": "Bootcamp SmartPLS", "rating": 5,
     "comment": "SEM yang tadinya terasa sangat rumit jadi mudah dimengerti. Langsung bisa saya terapkan di tesis saya. Fasilitatornya sabar dan menjelaskan dengan sangat baik!"},
    {"name": "Dimas Santoso", "role": "Peneliti Muda, Lembaga Riset Independen", "program_name": "Konsultasi AJI Statistik", "rating": 5,
     "comment": "Konsultasi analisis data sangat profesional. Tim membantu dari pemilihan metode hingga interpretasi hasil. Artikel saya berhasil diterima jurnal Sinta 2!"},
    {"name": "Putri Handayani", "role": "Mahasiswi S1 Psikologi, UI", "program_name": "Short Class Validitas SPSS", "rating": 5,
     "comment": "2 jam yang sangat padat tapi mudah dipahami. Uji validitas instrumen skripsi saya jadi lebih percaya diri. Worth it banget!"},
    {"name": "Arif Budiman", "role": "Dosen Muda, Universitas Brawijaya", "program_name": "Bootcamp Publikasi Scopus", "rating": 5,
     "comment": "Strategi penulisan yang diajarkan sangat praktikal. Artikel pertama saya akhirnya diterima jurnal Q2 Scopus setelah mengikuti bootcamp ini."},
    {"name": "Maya Lestari", "role": "Mahasiswi Doktoral, IPB University", "program_name": "Bootcamp R Studio", "rating": 5,
     "comment": "Materinya komprehensif dan update. Visualisasi dengan ggplot2 yang saya pelajari langsung dipakai untuk disertasi saya. Highly recommended!"},
]

for t in testimonials:
    Testimonial.objects.create(**t)

print(f"✓ Created {len(testimonials)} testimonials")
print("✓ Seed data complete!")
